defaults:
  - _self_
  - datasets: Higgs

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 3e-4
  activation: ReLU
  latent_dim: 9
  output_activation: Identity
  beta: 1e-6
  weight_decay: 1e-7

  hidden_layers: [256, 128, 64, 32]

  anneal_type: False
  anneal_kwargs:
    n_epoch: 201
    ramp_y_step: 0.02

  use_resnet: False

logger_config:
  experiment_name: TEST
  run_name: bVAE
  model_name: Higgs_bVAE
  early_stop_dict: 
    monitor: val_loss
    mode: min
    patience: 15

trainer_config: 
  gpus: 1 
  max_epochs: 201
  num_sanity_val_steps: 0