defaults:
  - _self_
  - datasets: MNIST

hydra:  
  output_subdir: null  
  run:  
    dir: .

model_config:
  learning_rate: 3e-4
  activation: ReLU
  latent_dim: 64
  output_activation: Identity
  beta: 1.0
  weight_decay: 1e-7

  hidden_layers: [128, 128, 128]

  use_resnet: True

  vec_sigma: False
  mse_sigma: False

  anneal_type: False
  anneal_kwargs:
    n_epoch: 201
    ramp_y_step: 0.02

logger_config:
  experiment_name: TEST
  run_name: sigmaVAE
  model_name: MNIST_sigmaVAE
  early_stop_dict: 
    monitor: val_loss
    mode: min
    patience: 15

trainer_config: 
  gpus: 1 
  max_epochs: 101
  num_sanity_val_steps: 0